import base from "./base.js";

/** ESLint config for the Next.js app, layered on the shared base. */
export default [
  ...base,
  {
    // Auto-generated by Next.js; not meant to be edited or linted.
    ignores: ["**/next-env.d.ts"],
  },
];
